import{S as c,i as l}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function p(a){const t="https://pixabay.com/api/",n=`?key=43825908-e00f2a501e8ab3b01ba78a8cd&q=${a}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(`${t}${n}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function u(a,t){const s=a.reduce((n,e)=>n+=`<div class="gallery-item">
            <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"  width="360"/></a>
            <div class="info">
                <p>Likes <span></span>${e.likes}</span></p>
                <p>Views <span></span>${e.views}</span></p>
                <p>Comments <span></span>${e.comments}</span></p>
                <p>Downloads <span></span>${e.downloads}</span></p>
            </div>
                </div>`,"");t.insertAdjacentHTML("beforeend",s)}const o={formEL:document.querySelector("#form"),inputEL:document.querySelector("#image-input"),galleryEL:document.querySelector("#gallery"),gallery:document.querySelector(".gallery")};let d=new c("#gallery a",{captionsData:"alt",captionDelay:250});function g(a){a.preventDefault(),o.galleryEL.innerHTML='<span class="loader"></span>';const t=o.inputEL.value.trim();if(t==="")return o.galleryEL.innerHTML="",l.show({title:'<div class="error-remark"><img src="./img/error.svg" alt="error" class="error-svg"><span class="error-text">Introduction field please enter the value to search</span></div>',titleSize:"20px",message:"",backgroundColor:"red",position:"topRight"});p(t).then(s=>{if(s.totalHits===0)return o.galleryEL.innerHTML="",l.show({title:'<div class="error-remark"><img src="./img/error.svg" alt="error" class="error-svg"><span class="error-text">Sorry, there are no images matching your search query. Please try again!</span></div>',titleSize:"20px",message:"",backgroundColor:"red",position:"topRight"});o.galleryEL.innerHTML="",u(s.hits,o.galleryEL),d.refresh()}).catch(s=>{o.galleryEL.innerHTML="",l.show({title:'<div class="error-remark"><img src="./img/error.svg" alt="error" class="error-svg"><span class="error-text">An error occurred while fetching the images. Please try again later.</span></div>',titleSize:"20px",message:"",backgroundColor:"red",position:"topRight"}),console.error("Error fetching images:",s)}),o.formEL.reset()}o.formEL.addEventListener("submit",g);
//# sourceMappingURL=commonHelpers.js.map
